before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
 - github:
     owner: timothystiles
     name: homebrew-ga-sandbox
   folder: Formula
   homepage: https://github.com/TimothyStiles/poly
   description: A test for goreleaser.
   test: |
     system "#{bin}/poly -h"
   dependencies:
   - name: go
   commit_author:
     name: Tim
     email: TimothyStiles@users.noreply.github.com
